using DTO.User;
using ENTITIES.Identifiers;

namespace CORE.Abstract;

/// <summary>
///     JWT minting + reading helper. <see cref="CreateTokenForUser" /> issues access tokens
///     for the auth flow; the various <c>GetXFromToken</c> methods read claims off the current
///     inbound bearer token. Refresh tokens are random opaque strings generated by
///     <see cref="GenerateRefreshToken" />.
/// </summary>
public interface IJwtService
{
    IssuedAccessToken CreateTokenForUser(UserToListDto user, DateTime expirationDate);
    public string? GetTokenString();
    public bool IsValidToken();
    public UserId? GetUserIdFromToken();

    /// <summary>
    ///     Returns the <c>jti</c> claim of the current inbound JWT, or <c>null</c> when the
    ///     header is missing or the claim is absent / malformed. Used by
    ///     <c>ValidateTokenFilter</c> and the logout flow as the persisted-token key.
    /// </summary>
    public Guid? GetJtiFromToken();

    public string GenerateRefreshToken();
    public string? GetRoleFromToken();
    public string TrimToken(string? jwtToken);
}

/// <summary>
///     Pair returned by <see cref="IJwtService.CreateTokenForUser" />: the encoded JWT string
///     handed back to the client, and the <c>jti</c> Guid the server persists for revocation /
///     introspection. The plain JWT never lands in the database.
/// </summary>
public sealed record IssuedAccessToken(string Jwt, Guid Jti);