using DTO.User;

namespace CORE.Abstract;

/// <summary>
///     JWT minting + reading helper. <see cref="CreateTokenForUser" /> issues access tokens
///     for the auth flow; the various <c>GetXFromToken</c> methods read claims off the current
///     inbound bearer token. Refresh tokens are random opaque strings generated by
///     <see cref="GenerateRefreshToken" />.
/// </summary>
public interface IJwtService
{
    string CreateTokenForUser(UserToListDto user, DateTime expirationDate);
    public string? GetTokenString();
    public bool IsValidToken();
    public Guid? GetUserIdFromToken();
    public string GenerateRefreshToken();
    public string? GetRoleFromToken();
    public string TrimToken(string? jwtToken);
}