<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <CodeAnalysisRuleSet>../settings.ruleset</CodeAnalysisRuleSet>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Newtonsoft.Json"/>
        <None Remove="Microsoft.AspNetCore.Cryptography.KeyDerivation"/>
        <None Remove="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <None Remove="Middlewares\TokenMiddleware\"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.4.1"/>
        <PackageReference Include="itext" Version="9.6.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8"/>
        <PackageReference Include="MongoDB.Driver" Version="3.9.0"/>
        <PackageReference Include="System.Drawing.Common" Version="10.0.8"/>
        <PackageReference Include="StackExchange.Redis" Version="2.13.17"/>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8"/>
        <PackageReference Include="LaunchDarkly.ServerSdk" Version="8.14.0"/>
        <PackageReference Include="Npgsql" Version="10.0.3"/>
        <PackageReference Include="System.IO.Hashing" Version="10.0.8"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\DTO\DTO.csproj"/>
    </ItemGroup>
</Project>
