<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <CodeAnalysisRuleSet>../settings.ruleset</CodeAnalysisRuleSet>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Newtonsoft.Json"/>
        <None Remove="Microsoft.AspNetCore.Cryptography.KeyDerivation"/>
        <None Remove="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <None Remove="Middlewares\TokenMiddleware\"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.2.2"/>
        <PackageReference Include="itext" Version="9.4.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1"/>
        <PackageReference Include="MongoDB.Driver" Version="3.5.2"/>
        <PackageReference Include="SSH.NET" Version="2025.1.0"/>
        <PackageReference Include="System.Drawing.Common" Version="10.0.1"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\DTO\DTO.csproj"/>
    </ItemGroup>
</Project>
