<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <CodeAnalysisRuleSet>../settings.ruleset</CodeAnalysisRuleSet>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Newtonsoft.Json"/>
        <None Remove="Microsoft.AspNetCore.Cryptography.KeyDerivation"/>
        <None Remove="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <None Remove="Middlewares\TokenMiddleware\"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
        <PackageReference Include="MongoDB.Driver" Version="3.4.0" />
        <PackageReference Include="SSH.NET" Version="2025.0.0" />
        <PackageReference Include="System.Drawing.Common" Version="9.0.5" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\DTO\DTO.csproj"/>
    </ItemGroup>
</Project>
