<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <CodeAnalysisRuleSet>../settings.ruleset</CodeAnalysisRuleSet>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="AutoMapper.Extensions.Microsoft.DependencyInjection"/>
        <None Remove="StyleCop.Analyzers"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\CORE\CORE.csproj"/>
        <ProjectReference Include="..\DAL\DAL.csproj"/>
        <ProjectReference Include="..\DTO\DTO.csproj"/>
        <ProjectReference Include="..\ENTITIES\ENTITIES.csproj"/>
        <ProjectReference Include="..\NOTIFICATIONS\NOTIFICATIONS.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.1.1"/>
    </ItemGroup>
</Project>
